### ISSUE TITLE
How to add option to save in pdf/png?

### ISSUE THREAD

**Issue by nmrcardoso** [user1095108/cairowidget#1]
Thanks a lot for the code.

Can you please add support to save all window or just one widget to pdf/png...

thanks

**Comment by user1095108** [comment]
This is really trivial, I've updated the example with your request and I leave the .pdf capture to you as your homework.

**Comment by nmrcardoso** [comment]
Thanks a lot.
Sorry, but I think I was not so explicit, sorry about that.
Imagine if you have more than one widget:

Fl_Group *group = new Fl_Group(0,0,724, 700);
group->begin();
  auto const ex(new CairoWidget(0, 0, win->w()/2, win->h()/2));
  auto const ex1(new CairoWidget(win->w()/2, 0, win->w()/2, win->h()/2));
  auto const ex2(new CairoWidget(0, win->h()/2, win->w()/2, win->h()/2));
  auto const ex3(new CairoWidget(win->w()/2, win->h()/2, win->w()/2, win->h()/2));
group->end();
  win->end();

can you provide a solution to print all the widgets/all window as one image/pdf/svg?
The solution you provided is good to print only one widget, however I have some 
problems implementing the print of the window, all widgets together.
Sorry, I'm new to fltk and cairo, and your solution seems to me the best one to create widgets in cairo context

Thanks a lot.

**Comment by user1095108** [comment]
I can only give a generic reply since, I really don't need this feature. I'd start reading here and see how Fl_Double_Window does off-screen rendering, check the source code of course.

https://www.fltk.org/doc-1.3/drawing.html#ssect_Offscreen

Then I'd change the CairoWidget to render into an image and then paste that image via fl_draw_image().

https://www.fltk.org/doc-1.3/group__fl__drawings.html

This would make CairoWidget a regular fltk widget, containing absolutely no hacks. After that I'd make use of this knowledge to create a screenshot of selected widgets (i.e. I'd render them into an off-screen image, then save that image somewhere).

On the other hand, you can also use the fltk-provided:
https://www.fltk.org/doc-1.3/classFl__Cairo__Window.html

and try to use that. I posted CairoWidget to mostly give users ideas and a starting point for adaptation. I really can't help you further, as I don't need the hacks I suggested personally.

**Comment by user1095108** [comment]
I wrote an example of what a portable cairo widget might look like.

**Comment by user1095108** [comment]
Hey, I added CairoWindow for ripping speed, try it. The speed improvement really show, but you'll have to compile cairo with opengl support yourself.

**Comment by user1095108** [comment]
You need to use this with the portable widget:

`void Fl_Image_Surface::draw(Fl_Widget *widget, int delta_x, int delta_y)`
