### ISSUE TITLE
Improve building for dummies ;)

### ISSUE THREAD

**Issue by wcout** [user1095108/cairowidget#2]
Looks there are some interesting ideas contained in this project...
But obviously you are targeting `Windows `- there are some case problems with include files :  `.h` instead of `.H`, `Fl_` instead of `FL_` that make it hard to try it on Linux.

Also there seems to be a requirement to have a .`./cairo` directory. What's that?

How do you build it?

**Comment by user1095108** [comment]
I'm using arch linux, ../cairo/ is a custom build of cairo, that includes the opengl backend. By default, arch does not provide a build of cairo, that has it. If I do:

`g++ -std=c++20 -Ofast -I./nanosvg/src example1.cpp cairowidget.cpp cairosvgutils.cpp -o example1 -lfltk -lcairo
`
the example builds fine, otherwise install boost build: aur/boost-build 4.0.1-1 (+32 0.00) (Installed: 4.1.0-1)

Just throw the ..cairo part out, if it is causing problems. I have no other way to build the opengl example, than to use my custom build, there is nothing in the AUR.

**Comment by user1095108** [comment]
Oh, BTW, I'm a fan of your sunrise demo. The opengl backend would make it render so much faster (if it worked 100%, which it doesn't).

**Comment by user1095108** [comment]
Don't forget `git submodule init` and `git submodule update`

**Comment by wcout** [comment]
Oh, so arch linux must have some magic to find the proper include files - there are no .h files in FLTK.
Thanks for the additional instructions, they work so far, but I am currently on Ubuntu 16.04 and don't have a c++20 compiler - will try later on another machine..

**Comment by user1095108** [comment]
I wasn't aware of the header file issue, arch creates symbolic links from
.H to .h automatically and I thought it was so everywhere, as for c++20,
this is why I use arch. Always there's the latest and greatest available on
arch.

**Comment by wcout** [comment]
The standard is another thing.. Certainly pretty cool if one knows it, but a nightmare for someone like me, who just is fluent with c++03! :(

**Comment by user1095108** [comment]
I'm pretty sure you could get away with `-std=c++2a`. But hey, it's 2020 :)

**Comment by wcout** [comment]
Yeah, but the code base I use to maintain is from 1996, so I'm already far in the future for my needs ;)

**Comment by user1095108** [comment]
Ah, those were the days...
